### ISSUE TITLE
API createPoint

### ISSUE THREAD

**Issue by elagin** [rjhdby/MotoTimes.motobat.server#3]
Ждемс.

**Comment by elagin** [comment]
Пожалуйста, переделай userId на ownerid и добавь ownername.

**Comment by elagin** [comment]
и поле для адреса

**Comment by rjhdby** [comment]
Адрес не нужен, я так полагаю
https://github.com/rjhdby/MotoTimes.motobat.server/issues/2

ownername из VK берется, не?

**Comment by elagin** [comment]
Мой ownername берется из ВК, а как я узнаю кто создал чужую точку? Буду по его owner_id каждый раз при загрузке точек на сервере ВКспрашивать? Поэтому и нужно, чтобы клиент при создании точки сообщал свой ownername, а сервер его отдавал.

Адрес-то чем помешал?

**Comment by rjhdby** [comment]
Ну не вопрос. А нафига адрес туда-сюда гонять и базе держать, когда родные гугловские сервисы адрес по точке выдают на ура.
Тем паче, что я вообще не вижу смысла в адресе, все же на карте.
