### ISSUE TITLE
API getPointList

### ISSUE THREAD

**Issue by elagin** [rjhdby/MotoTimes.motobat.server#4]

**Comment by elagin** [comment]
Пожалуйста, переобзови lng в lon, так привычнее.

**Comment by elagin** [comment]
И добавь ownername

**Comment by elagin** [comment]
и поле для адреса

**Comment by rjhdby** [comment]
Он повсюду lng обзывается, только у нас lon

**Comment by rjhdby** [comment]
Адрес https://github.com/rjhdby/MotoTimes.motobat.server/issues/2

**Comment by elagin** [comment]
Уж я-то много лет с навигационным софом работаю и везде lat и lon. Вероятно потому что буквы подряд стоят.
Тогда уж ltt и lng сделаем :)
